Prefix: "&7[&6EInv&7] |"

# If this option is enabled, the hotbar items will also be changed by switching pages
IncludeHotbarItems: false

InventoryConfiguration:
  NextPageItem:
    Name: "&aNext Page"
    Material: "arrow"
    # You can split the lines by using '//'
    Lore: "//&7Navigate to the next//&7page of your inventory"
    # If you want to use custom skins on your items, you can put in minecrafturl-values from: https://minecraft-heads.com
    MinecraftURL: "77334cddfab45d75ad28e1a47bf8cf5017d2f0982f6737da22d4972952510661"
  PreviousPageItem:
    Name: "&aPrevious Page"
    Material: "arrow"
    # You can split the lines by using '//'
    Lore: "//&7Navigate to the previous//&7page of your inventory"
    # If you want to use custom skins on your items, you can put in minecrafturl-values from: https://minecraft-heads.com
    MinecraftURL: "e7742034f59db890c8004156b727c77ca695c4399d8e0da5ce9227cf836bb8e2"
  IndicatorItem:
    Name: "&7Page: (&e%PAGE%&7)"
    Material: "gray_stained_glass_pane"
    # You can split the lines by using '//'
    Lore: ""
    # You can find Minecraft-URL-Values here: https://minecraft-heads.com
    MinecraftURL: ""